apiVersion: v1
kind: Pod
metadata:
  name: sharma-jenga
  namespace: fbiessmann
spec:
  restartPolicy: OnFailure
  containers:
  - name: sharma-jenga
    image: registry.datexis.com/s77220/sharma-jenga:latest
    ports:
    - name: client-port
      containerPort: 5000
    resources:
      requests:
        nvidia.com/gpu: 1
        cpu: 1
      limits:
        memory: 36Gi
        nvidia.com/gpu: 1
        cpu: 2
  imagePullSecrets:
    - name: private-registry-auth
  nodeSelector:
    gpu: p100
