apiVersion: v1
kind: Pod
metadata:
  name: jenga-experiments1
  namespace: fbiessmann
spec:
  restartPolicy: OnFailure
  containers:
  - name: jenga-experiments
    image: registry.datexis.com/s77220/jenga-experiments:latest
    ports:
    - name: client-port
      containerPort: 5000
    resources:
      limits:
        memory: 125Gi
  imagePullSecrets:
    - name: private-registry-auth
