apiVersion: v1
kind: Pod
metadata:
  name: jenga-fractions-v
  namespace: fbiessmann
spec:
  restartPolicy: OnFailure
  containers:
  - name: jenga-fractions
    image: registry.datexis.com/s77220/jenga-fractions:latest
    ports:
    - name: client-port
      containerPort: 5000
    resources:
      limits:
        memory: 125Gi
        nvidia.com/gpu: 2
  imagePullSecrets:
    - name: private-registry-auth
  nodeSelector:
    gpu: v100
